pub mod example_01_setup;
#[path = "02-machine-context.rs"]
pub mod example_02_machine_context;
#[path = "03-derives.rs"]
pub mod example_03_derives;
#[path = "04-transitions.rs"]
pub mod example_04_transitions;
#[path = "05-split-transition.rs"]
pub mod example_05_split_transition;
#[path = "06-async-transitions.rs"]
pub mod example_06_async_transitions;
#[path = "07-state-data.rs"]
pub mod example_07_state_data;
#[path = "08-transition-with-data.rs"]
pub mod example_08_transition_with_data;
#[path = "09-persistent-data.rs"]
pub mod example_09_persistent_data;
#[path = "10-persistent-data-vecs.rs"]
pub mod example_10_persistent_data_vecs;
#[path = "11-hierarchical-machines.rs"]
pub mod example_11_hierarchical_machines;
#[path = "12-rollbacks.rs"]
pub mod example_12_rollbacks;
#[path = "13-review-flow.rs"]
pub mod example_13_review_flow;
